name: ğŸš€ Deployment
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: â¬£ ESLint
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
      NX_BRANCH: ${{GITHUB_HEAD_REF}}
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¦ Install pnpm & deps
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v3
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
          echo "BRANCH: ${{ env.NX_BRANCH }}"

      - run: pnpm install --frozen-lockfile

      - name: ğŸ”¬ Lint
        run: npx nx affected --target=lint --parallel=3

  vitest:
    name: ğŸƒ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¦ Install pnpm & deps
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: ğŸƒ Run Vitest
        run: pnpm test

  build:
    name: ğŸ—ï¸ Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¦ Install pnpm & deps
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: ğŸƒ Build
        run: pnpm build

      - name: Archive app build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist_app
          path: |
            packages/app/dist
          retention-days: 2

      - name: Archive lib build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist_lib
          path: |
            packages/lib/dist
          retention-days: 2
